---
# Source: factorio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-factorio
  labels:
    app: release-name-factorio
    chart: "factorio-0.4.0"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  server-password: ""
  rcon-password: ""
  factorio-username: "eW91ci51c2VybmFtZQ=="
  factorio-password: "eW91ci5wYXNzd29yZA=="

---
# Source: factorio/templates/saves-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-factorio-savedgames
  labels:
    app: release-name-factorio
    chart: "factorio-0.4.0"
    release: "release-name"
    heritage: "Tiller"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
# Source: factorio/templates/factorio-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-factorio
  labels:
    app: release-name-factorio
    chart: "factorio-0.4.0"
    release: "release-name"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  ports:
  - name: factorio
    port: 34197
    targetPort: factorio
    protocol: UDP
  selector:
    app: release-name-factorio

---
# Source: factorio/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-name-factorio
  labels:
    app: release-name-factorio
    chart: "factorio-0.4.0"
    release: "release-name"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: release-name-factorio
    spec:
      containers:
      - name: release-name-factorio
        image: "quay.io/games_on_k8s/factorio:0.15.39"
        imagePullPolicy: Always
        resources:
          requests:
            memory: 512Mi
          
        env:
        - name: FACTORIO_SERVER_NAME
          value: "Kubernetes Server"
        - name: FACTORIO_DESCRIPTION
          value: "Factorio running on Kubernetes"
        - name: FACTORIO_PORT
          value: "34197"
        - name: FACTORIO_MAX_PLAYERS
          value: "255"
        - name: FACTORIO_IS_PUBLIC
          value: "false"
        - name: FACTORIO_REQUIRE_USER_VERIFICATION
          value: "false"
        - name: FACTORIO_ALLOW_COMMANDS
          value: "admins-only"
        - name: FACTORIO_NO_AUTO_PAUSE
          value: "false"
        - name: FACTORIO_AUTOSAVE_INTERVAL
          value: "2"
        - name: FACTORIO_AUTOSAVE_SLOTS
          value: "3"

        ports:
        - name: factorio
          containerPort: 34197
          protocol: UDP
        volumeMounts:
        - name: saves
          mountPath: /opt/factorio/saves
        - name: mods
          mountPath: /opt/factorio/mods
      volumes:
      - name: saves
        persistentVolumeClaim:
          claimName: release-name-factorio-savedgames
      - name: mods
        emptyDir: {}

---
# Source: factorio/templates/mods-pvc.yaml

---
# Source: factorio/templates/rcon-svc.yaml


